{% set name = "pgvector-python" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pgvector/pgvector-python/archive/v{{ version }}.tar.gz
  sha256: f5f4b100b5892a320579ac2120ec3a3a7c82dc6f48397a215f86313c9e406256

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - numpy
    - pgvector
    - postgresql
  run:
    - python >=3.8
    - pip
    - numpy
    - pgvector
    - postgresql

test:
  imports:
    - pgvector
  commands:
    - pip check

about:
  home: https://github.com/pgvector/pgvector-python
  summary: pgvector support for Python
  description: |
    pgvector support for Python.
    Great for online recommendations.
    Supports Django, SQLAlchemy, Psycopg 3, Psycopg 2, and asyncpg.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://pypi.org/project/pgvector/
  dev_url: https://github.com/pgvector/pgvector-python

extra:
  recipe-maintainers:
    - mmcauliffe
