schema_version: 1

context:
  version: "0.5.1"

package:
  name: pgvector-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pgvector/pgvector-${{ version }}.tar.gz
  sha256: 94998a54b801b1075d623b8fa677fcb8210a7977b88f8e2203ab115c155af2e4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy

tests:
  - python:
      imports:
        - pgvector
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: pgvector support for Python
  description: |
    pgvector support for Python.
    Great for online recommendations.
    Supports Django, SQLAlchemy, Psycopg 3, Psycopg 2, asyncpg, pg8000, and Peewee.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/pgvector/pgvector-python
  repository: https://github.com/pgvector/pgvector-python
  documentation: https://pypi.org/project/pgvector/

extra:
  recipe-maintainers:
    - mmcauliffe
    - moritzwilksch
